#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
import maidenhead as mh
import pandas as pd

import os
from sys import argv

data = pd.DataFrame()
# (optional) remove limited number of rows to be displayed
#pd.set_option('display.max_rows', None)

# open the WSJT-X log file
with open(argv[1], 'r') as fh:
    lat = 0
    lon = 0
    i = 0
    for line in fh:
        # remove superfluous spaces, and split string into components
        fields = ' '.join(line.split()).split(' ')
        # look for CQ calls
        if fields[7] != 'CQ':
            continue
        maidenhead = fields[len(fields)-1]
        callsign = fields[len(fields)-2]
        # ensure that maidenhead is in proper format
        if len(maidenhead) == 4 or len(maidenhead) == 6:
            # convert to lat/lon and store to dataframe
            loc = mh.to_location(maidenhead)
            data = data.append( pd.DataFrame({"Timestamp":fields[0],
                                              "Frequency":fields[1],
                                              "Mode":fields[3],
                                              "Callsign":callsign,
                                              "Maidenhead":maidenhead,
                                              "Latitude":loc[0],
                                              "Longitude":loc[1],
                                              "SNR":fields[4]},
                                              index=[i]))
            i += 1

print(data)
data.to_csv('this.csv',index=True)
